<?php

use yii\db\Migration;

class m210813_181458_heatmap extends Migration
{
    public function safeUp() {
        $sql = <<<SQL
        
        INSERT INTO `bpbi_grafico_configuracao` (`view`,`tipo`,`data`,`data_serie`,`is_serie`,`data_timeline`) VALUES ('content','heatmap','{tooltip:{position:\'top\', formatter: function (params,ticket,callback) { var res = params.name.substring(0, 50);  res += \' : \' + _prepend + formatData(params.value[2], _tipo, true) + _pospend; return res; }},grid:{x: \'200px\', y: \'50px\', x2: \'50px\', y2: \'50px\'},xAxis:{type:\'category\',data:_z,splitArea:{show:true}},yAxis:{type:\'category\',data:_x,splitArea:{show:true}},visualMap:{show:false, max: _max, calculable:true,orient:\'horizontal\',left: \'center\', bottom:\'20px\', formatter: function (value) { return _prepend + formatData(value, _tipo, false) + _pospend; }},series:[{type:\'heatmap\',data:_values,label:{show:false, formatter: function (params) { return _prepend + formatData(params.value[2], _tipo, false) + _pospend; }},emphasis:{itemStyle:{shadowBlur:10,shadowColor:\'rgba(0, 0, 0, 0.5)\'}}}]}','',0,NULL);
        INSERT INTO `bpbi_grafico_configuracao` (`view`,`tipo`,`data`,`data_serie`,`is_serie`,`data_timeline`) VALUES ('view','heatmap','{tooltip:{position:\'top\', formatter: function (params,ticket,callback) { var res = params.name.substring(0, 50);  res += \' : \' + _prepend + formatData(params.value[2], _tipo, true) + _pospend; return res; }},grid:{x: \'200px\', y: \'50px\', x2: \'50px\', y2: \'150px\'}, toolbox: {show: true, orient: \'vertical\', y: \'bottom\', feature: {restore: {show: true, title: \'.\'},dataZoom: {show: true, title: {zoom: \'\', back: \'\' }}, saveAsImage: { show: true,backgroundColor: \'#FFF\',title: \'\', excludeComponents: [\'toolbox\', \'dataZoom\'], name: \' \'+_filename+\' - \'+_data.nomes[\'y\']}}},xAxis:{type:\'category\',data:_z,splitArea:{show:true}},yAxis:{type:\'category\',data:_x,splitArea:{show:true}},visualMap:{show:true, max: _max, calculable:true,orient:\'horizontal\',left: \'center\', bottom:\'20px\', formatter: function (value) { console.log(value); return _prepend + formatData(value, _tipo, false) + _pospend; }},series:[{type:\'heatmap\',data:_values,label:{show:false, formatter: function (params) { return _prepend + formatData(params.value[2], _tipo, false) + _pospend; }},emphasis:{itemStyle:{shadowBlur:10,shadowColor:\'rgba(0, 0, 0, 0.5)\'}}}]}','',0,NULL);
        INSERT INTO `bpbi_grafico_configuracao` (`view`,`tipo`,`data`,`data_serie`,`is_serie`,`data_timeline`) VALUES ('preview','heatmap','{tooltip:{position:\'top\', formatter: function (params,ticket,callback) { var res = params.name.substring(0, 50);  res += \' : \' + _prepend + formatData(params.value[2], _tipo, true) + _pospend; return res; }},grid:{x: \'200px\', y: \'50px\', x2: \'50px\', y2: \'50px\'},xAxis:{type:\'category\',data:_z,splitArea:{show:true}},yAxis:{type:\'category\',data:_x,splitArea:{show:true}},visualMap:{show:false, max: _max, calculable:true,orient:\'horizontal\',left: \'center\', bottom:\'20px\', formatter: function (value) { return _prepend + formatData(value, _tipo, false) + _pospend; }},series:[{type:\'heatmap\',data:_values,label:{show:false, formatter: function (params) { return _prepend + formatData(params.value[2], _tipo, false) + _pospend; }},emphasis:{itemStyle:{shadowBlur:10,shadowColor:\'rgba(0, 0, 0, 0.5)\'}}}]}','',0,NULL);
        INSERT INTO `bpbi_grafico_configuracao` (`view`,`tipo`,`data`,`data_serie`,`is_serie`,`data_timeline`) VALUES ('mobile','heatmap','{tooltip:{position:\'top\', formatter: function (params,ticket,callback) { var res = params.name.substring(0, 50);  res += \' : \' + _prepend + formatData(params.value[2], _tipo, true) + _pospend; return res; }},grid:{x: \'200px\', y: \'50px\', x2: \'50px\', y2: \'50px\'},xAxis:{type:\'category\',data:_z,splitArea:{show:true}},yAxis:{type:\'category\',data:_x,splitArea:{show:true}},visualMap:{show:false, max: _max, calculable:true,orient:\'horizontal\',left: \'center\', bottom:\'20px\', formatter: function (value) { return _prepend + formatData(value, _tipo, false) + _pospend; }},series:[{type:\'heatmap\',data:_values,label:{show:false, formatter: function (params) { return _prepend + formatData(params.value[2], _tipo, false) + _pospend; }},emphasis:{itemStyle:{shadowBlur:10,shadowColor:\'rgba(0, 0, 0, 0.5)\'}}}]}','',0,NULL);
        INSERT INTO `bpbi_grafico_configuracao` (`view`,`tipo`,`data`,`data_serie`,`is_serie`,`data_timeline`) VALUES ('share','heatmap','{tooltip:{position:\'top\', formatter: function (params,ticket,callback) { var res = params.name.substring(0, 50);  res += \' : \' + _prepend + formatData(params.value[2], _tipo, true) + _pospend; return res; }},grid:{x: \'200px\', y: \'50px\', x2: \'50px\', y2: \'150px\'}, toolbox: {show: true, orient: \'vertical\', y: \'bottom\', feature: {restore: {show: true, title: \'.\'},dataZoom: {show: true, title: {zoom: \'\', back: \'\' }}, saveAsImage: { show: true,backgroundColor: \'#FFF\',title: \'\', excludeComponents: [\'toolbox\', \'dataZoom\'], name: \' \'+_filename+\' - \'+_data.nomes[\'y\']}}},xAxis:{type:\'category\',data:_z,splitArea:{show:true}},yAxis:{type:\'category\',data:_x,splitArea:{show:true}},visualMap:{show:true, max: _max, calculable:true,orient:\'horizontal\',left: \'center\', bottom:\'20px\', formatter: function (value) { console.log(value); return _prepend + formatData(value, _tipo, false) + _pospend; }},series:[{type:\'heatmap\',data:_values,label:{show:false, formatter: function (params) { return _prepend + formatData(params.value[2], _tipo, false) + _pospend; }},emphasis:{itemStyle:{shadowBlur:10,shadowColor:\'rgba(0, 0, 0, 0.5)\'}}}]}',NULL,0,NULL);
        INSERT INTO `bpbi_grafico_configuracao` (`view`,`tipo`,`data`,`data_serie`,`is_serie`,`data_timeline`) VALUES ('content','heatmap','{tooltip:{position:\'top\', formatter: function (params,ticket,callback) { var res = params.name.substring(0, 50);  res += \' : \' + _prepend + formatData(params.value[2], _tipo, true) + _pospend; return res; }},grid:{x: \'200px\', y: \'50px\', x2: \'50px\', y2: \'50px\'},xAxis:{type:\'category\',data:_z,splitArea:{show:true}},yAxis:{type:\'category\',data:_x,splitArea:{show:true}},visualMap:{show:false, max: _max, calculable:true,orient:\'horizontal\',left: \'center\', bottom:\'20px\', formatter: function (value) { return _prepend + formatData(value, _tipo, false) + _pospend; }},series:[{type:\'heatmap\',data:_values,label:{show:false, formatter: function (params) { return _prepend + formatData(params.value[2], _tipo, false) + _pospend; }},emphasis:{itemStyle:{shadowBlur:10,shadowColor:\'rgba(0, 0, 0, 0.5)\'}}}]}','',1,NULL);
        INSERT INTO `bpbi_grafico_configuracao` (`view`,`tipo`,`data`,`data_serie`,`is_serie`,`data_timeline`) VALUES ('view','heatmap','{tooltip:{position:\'top\', formatter: function (params,ticket,callback) { var res = params.name.substring(0, 50);  res += \' : \' + _prepend + formatData(params.value[2], _tipo, true) + _pospend; return res; }},grid:{x: \'200px\', y: \'50px\', x2: \'50px\', y2: \'150px\'}, toolbox: {show: true, orient: \'vertical\', y: \'bottom\', feature: {restore: {show: true, title: \'.\'},dataZoom: {show: true, title: {zoom: \'\', back: \'\' }}, saveAsImage: { show: true,backgroundColor: \'#FFF\',title: \'\', excludeComponents: [\'toolbox\', \'dataZoom\'], name: \' \'+_filename+\' - \'+_data.nomes[\'y\']}}},xAxis:{type:\'category\',data:_z,splitArea:{show:true}},yAxis:{type:\'category\',data:_x,splitArea:{show:true}},visualMap:{show:true, max: _max, calculable:true,orient:\'horizontal\',left: \'center\', bottom:\'20px\', formatter: function (value) { console.log(value); return _prepend + formatData(value, _tipo, false) + _pospend; }},series:[{type:\'heatmap\',data:_values,label:{show:false, formatter: function (params) { return _prepend + formatData(params.value[2], _tipo, false) + _pospend; }},emphasis:{itemStyle:{shadowBlur:10,shadowColor:\'rgba(0, 0, 0, 0.5)\'}}}]}','',1,NULL);
        INSERT INTO `bpbi_grafico_configuracao` (`view`,`tipo`,`data`,`data_serie`,`is_serie`,`data_timeline`) VALUES ('preview','heatmap','{tooltip:{position:\'top\', formatter: function (params,ticket,callback) { var res = params.name.substring(0, 50);  res += \' : \' + _prepend + formatData(params.value[2], _tipo, true) + _pospend; return res; }},grid:{x: \'200px\', y: \'50px\', x2: \'50px\', y2: \'50px\'},xAxis:{type:\'category\',data:_z,splitArea:{show:true}},yAxis:{type:\'category\',data:_x,splitArea:{show:true}},visualMap:{show:false, max: _max, calculable:true,orient:\'horizontal\',left: \'center\', bottom:\'20px\', formatter: function (value) { return _prepend + formatData(value, _tipo, false) + _pospend; }},series:[{type:\'heatmap\',data:_values,label:{show:false, formatter: function (params) { return _prepend + formatData(params.value[2], _tipo, false) + _pospend; }},emphasis:{itemStyle:{shadowBlur:10,shadowColor:\'rgba(0, 0, 0, 0.5)\'}}}]}','',1,NULL);
        INSERT INTO `bpbi_grafico_configuracao` (`view`,`tipo`,`data`,`data_serie`,`is_serie`,`data_timeline`) VALUES ('mobile','heatmap','{tooltip:{position:\'top\', formatter: function (params,ticket,callback) { var res = params.name.substring(0, 50);  res += \' : \' + _prepend + formatData(params.value[2], _tipo, true) + _pospend; return res; }},grid:{x: \'200px\', y: \'50px\', x2: \'50px\', y2: \'50px\'},xAxis:{type:\'category\',data:_z,splitArea:{show:true}},yAxis:{type:\'category\',data:_x,splitArea:{show:true}},visualMap:{show:false, max: _max, calculable:true,orient:\'horizontal\',left: \'center\', bottom:\'20px\', formatter: function (value) { return _prepend + formatData(value, _tipo, false) + _pospend; }},series:[{type:\'heatmap\',data:_values,label:{show:false, formatter: function (params) { return _prepend + formatData(params.value[2], _tipo, false) + _pospend; }},emphasis:{itemStyle:{shadowBlur:10,shadowColor:\'rgba(0, 0, 0, 0.5)\'}}}]}','',1,NULL);
        INSERT INTO `bpbi_grafico_configuracao` (`view`,`tipo`,`data`,`data_serie`,`is_serie`,`data_timeline`) VALUES ('share','heatmap','{tooltip:{position:\'top\', formatter: function (params,ticket,callback) { var res = params.name.substring(0, 50);  res += \' : \' + _prepend + formatData(params.value[2], _tipo, true) + _pospend; return res; }},grid:{x: \'200px\', y: \'50px\', x2: \'50px\', y2: \'150px\'}, toolbox: {show: true, orient: \'vertical\', y: \'bottom\', feature: {restore: {show: true, title: \'.\'},dataZoom: {show: true, title: {zoom: \'\', back: \'\' }}, saveAsImage: { show: true,backgroundColor: \'#FFF\',title: \'\', excludeComponents: [\'toolbox\', \'dataZoom\'], name: \' \'+_filename+\' - \'+_data.nomes[\'y\']}}},xAxis:{type:\'category\',data:_z,splitArea:{show:true}},yAxis:{type:\'category\',data:_x,splitArea:{show:true}},visualMap:{show:true, max: _max, calculable:true,orient:\'horizontal\',left: \'center\', bottom:\'20px\', formatter: function (value) { console.log(value); return _prepend + formatData(value, _tipo, false) + _pospend; }},series:[{type:\'heatmap\',data:_values,label:{show:false, formatter: function (params) { return _prepend + formatData(params.value[2], _tipo, false) + _pospend; }},emphasis:{itemStyle:{shadowBlur:10,shadowColor:\'rgba(0, 0, 0, 0.5)\'}}}]}',NULL,1,NULL);
                
SQL;

        $this->execute($sql);

        return true;
    }

    public function safeDown() {
        echo "m190318_124125_themes cannot be reverted.\n";

        return true;
    }
}
